import scrapy


class QuotesSpider(scrapy.Spider):
    name = "quotes"

    def start_requests(self):
        urls = [
            # 'http://quotes.toscrape.com/page/1/',
            # 'http://quotes.toscrape.com/page/2/',
            'http://www.eatbydate.com/how-long-does-crab-last//',
            'http://www.eatbydate.com/fruits/fresh/apricots//',
             'http://www.eatbydate.com/fruits/dried-fruit-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/proteins/nuts/flax-seeds//',
            # 'http://www.eatbydate.com/baking-powder-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-wasabi-last-shelf-life/',
            # 'http://www.eatbydate.com/other/spice-menu/how-long-does-salt-last-shelf-life//',
            # 'http://www.eatbydate.com/proteins/meats/deli-meat-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-lemons-last//',
            # 'http://www.eatbydate.com/other/prescriptions//',
            # 'http://www.eatbydate.com/vegetables/frozen-vegetables-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/drinks/ensure//',
            # 'http://www.eatbydate.com/drinks/coffee-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/canned-vegetables-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/frozen-fruit-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/spinach/',
            # 'http://www.eatbydate.com/safe-to-stuff-a-turkey/',
            # 'http://www.eatbydate.com/how-long-does-chicken-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/salad-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-celery-last-shelf-life/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-does-pumpkin-last/',
            # 'http://www.eatbydate.com/eggs-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/fruits/fresh/bananas-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-powdered-milk-last-shelf-life//',
            # 'http://www.eatbydate.com/other/sweets/how-long-does-brown-sugar-last//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/kale/',
            # 'http://www.eatbydate.com/fish-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/baking-soda-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/honey-shelf-expiration-date//',
            # 'http://www.eatbydate.com/grains/baked-goods/stuffing-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-cupcakes-last-shelf-life//',
            # 'http://www.eatbydate.com/deli-meat-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/drinks/alcohol/wine-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/spreads/butter-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/cherries/', 'http://www.eatbydate.com/how-long-does-shrimp-last//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/cauliflower//',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-infant-formula-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com',
            # 'http://www.eatbydate.com/dairy/milk/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/grapes/', 'http://www.eatbydate.com/vegetables/',
            # 'http://www.eatbydate.com/how-to-read-food-labels/',
            # 'http://www.eatbydate.com/coffee-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-summer-squash-last/',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-condensed-milk-last-shelf-life/',
            # 'http://www.eatbydate.com/how-long-does-coffee-mate-last-shelf-life/',
            # 'http://www.eatbydate.com/proteins/nuts/flax-seeds/',
            # 'http://www.eatbydate.com/fruits/frozen-fruit-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/pie-shelf-life-expiration-date//', 'http://www.eatbydate.com/proteins/meats/',
            # 'http://www.eatbydate.com/cake-mix-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/baking/baking-soda-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-does-worcestershire-sauce-last-shelf-life//',
            # 'http://www.eatbydate.com/fruits/fresh/kiwi//', 'http://www.eatbydate.com/fruits/fresh/blueberries//',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-coconuts-last-shelf-life//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/broccoli/', 'http://www.eatbydate.com/other/snacks/',
            # 'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/drinks/fruit-juice-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/proteins/meats/hamburgers-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/can-you-freeze-cheese-2/',
            # 'http://www.eatbydate.com/proteins/poultry/how-long-does-chicken-broth-last-shelf-life//',
            # 'http://www.eatbydate.com/fruits/fresh/pomegranate/',
            # 'http://www.eatbydate.com/drinks/how-long-does-water-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/ice-cream-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/milk/', 'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-fish-sauce-last-shelf-life/',
            # 'http://www.eatbydate.com/other/condiments/how-long-do-capers-last-shelf-life/',
            # 'http://www.eatbydate.com/other/sweets/mms/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-garlic-last-shelf-life//',
            # 'http://www.eatbydate.com/stuffing-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/spaghetti-sauce-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/proteins/beans-peas/beans-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-oil-last//',
            # 'http://www.eatbydate.com/snacks/hummus/', 'http://www.eatbydate.com/terms-of-use/',
            # 'http://www.eatbydate.com/dairy/sour-cream-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/dairy/milk/soy-rice-almond-milk-substitutes-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/salsa-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/snacks/how-long-popcorn-last-shelf-life//',
            # 'http://www.eatbydate.com/fruits/fresh/honeydew//', 'http://www.eatbydate.com/sell-by-date-definition/',
            # 'http://www.eatbydate.com/proteins/meats/how-long-does-pork-last/',
            # 'http://www.eatbydate.com/how-long-does-syrup-last/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-garlic-last-shelf-life/',
            # 'http://www.eatbydate.com//other/condiments/olives/', 'http://www.eatbydate.com/other/baking/cornmeal/',
            # 'http://www.eatbydate.com/grains/stuffing-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/fruits/fresh/cherries/',
            # 'http://www.eatbydate.com/how-long-does-canned-meat-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-tortillas-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-frosting-last/',
            # 'http://www.eatbydate.com/how-long-does-winter-squash-last/',
            # 'http://www.eatbydate.com/fruits/fresh/grapefruit//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/',
            # 'http://www.eatbydate.com/what-is-the-proper-temperature-for-storing-wine/',
            # 'http://www.eatbydate.com/proteins/beans-peas/peas//',
            # 'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/spices/how-long-does-salt-last-shelf-life/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/cauliflower/',
            # 'http://www.eatbydate.com/how-long-do-marshmallows-last//',
            # 'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-cranberry-sauce-last/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-coconuts-last-shelf-life/',
            # 'http://www.eatbydate.com/ketchup-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/pudding-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/sweets/how-long-does-chocolate-syrup-last/',
            # 'http://www.eatbydate.com/fruits/fresh/mango//', 'http://www.eatbydate.com/dairy/spreads/',
            # 'http://www.eatbydate.com/how-long-does-garlic-last-shelf-life',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/eggplant//',
            # 'http://www.eatbydate.com/oreos-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/turkey-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/drinks/coffee-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-does-pumpkin-last//',
            # 'http://www.eatbydate.com/grains/pizza-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/chia-seeds//', 'http://www.eatbydate.com/other/spice-menu/',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-nutella-last-shelf-life/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/corn/',
            # 'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/potatoes-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-evaporated-milk-last-shelf-life//',
            # 'http://www.eatbydate.com/grains/lasagna//', 'http://www.eatbydate.com/how-long-do-clams-last//',
            # 'http://www.eatbydate.com/other/baking/how-long-does-molasses-last-shelf-life//',
            # 'http://www.eatbydate.com/fruits/fresh/apricots/"',
            # 'http://www.eatbydate.com/proteins/meats/ham-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/clean-a-sponge/',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-infant-formula-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-celery-last-shelf-life/',
            # 'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-lemons-last/',
            # 'http://www.eatbydate.com/dairy/cheese/brie-feta-mozzarella-soft-cheese-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-popcorn-last-shelf-life/',
            # 'http://www.eatbydate.com/drinks/alcohol/how-long-does-beer-last-shelf-life//',
            # 'http://www.eatbydate.com/proteins/meats/how-long-does-pork-last//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-do-sweet-potatoes-or-yams-last/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-limes-last//',
            # 'http://www.eatbydate.com/proteins/meats/bacon-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-does-evaporated-milk-last-shelf-life/',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-coffee-mate-last-shelf-life//',
            # 'http://www.eatbydate.com/canned-fruit-shelf-life-expiration-date//',
            # 'https://plus.google.com/share?url=http://www.eatbydate.com/vegetables/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/parsnips/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-lettuce-last//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/green-beans//',
            # 'http://www.eatbydate.com/fruits/fresh/figs//', 'http://www.eatbydate.com/fruits/fresh/pineapples',
            # 'http://www.eatbydate.com/wine-shelf-life-expiration-date/', 'http://www.eatbydate.com/grains/lasagna/',
            # 'http://www.eatbydate.com/how-long-does-fish-sauce-last-shelf-life/',
            # 'http://www.eatbydate.com/proteins/meats/hamburgers-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/cherries//',
            # 'http://www.eatbydate.com/drinks/alcohol/how-long-does-champagne-last-shelf-life//',
            # 'http://www.eatbydate.com/vegetables/canned-vegetables-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/how-long-do-spices-last//',
            # 'http://www.eatbydate.com/how-long-do-mussels-last//', 'http://www.eatbydate.com/blog-2/',
            # 'http://www.eatbydate.com/how-long-do-marshmallows-last/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-do-carrots-last-shelf-life/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/spaghetti-sauce-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-peanut-butter-last-shelf-life-expiration-date-food-storage//',
            # 'https://plus.google.com/share?url=http://www.eatbydate.com/fruits/',
            # 'http://www.eatbydate.com/proteins/meats/ham-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-jello-last-shelf-life/',
            # 'http://www.eatbydate.com/grains/cereal/cereal-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/drinks/sport-drinks-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/proteins/meats/bacon-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/broccoli//',
            # 'http://www.eatbydate.com/tomatoes-shelf-life-expiration-date',
            # 'http://www.eatbydate.com/dairy/ice-cream-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/sweets/how-long-does-cocoa-last-shelf-life//',
            # 'http://www.eatbydate.com/dairy/cheese/cheese-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/spaghetti-sauce-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/aspirin//', 'http://www.eatbydate.com/how-long-does-chocolate-syrup-last//',
            # 'http://www.eatbydate.com/sweets/oreos-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/drinks/sport-drinks-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/grapes', 'http://www.eatbydate.com/fresh-vegetables/corn//',
            # 'http://www.eatbydate.com/how-long-does-pork-last/',
            # 'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-carrots-last-shelf-life/',
            # 'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/dairy/cheese/cottage-cheese-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/chocolate-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/cottage-cheese-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-sweet-potatoes-or-yams-last/',
            # 'http://www.eatbydate.com/other/baking/cornmeal//',
            # 'http://www.eatbydate.com/drinks/fruit-juice-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-do-onions-last-shelf-life//',
            # 'http://www.eatbydate.com/other/sweets/how-long-does-cocoa-last-shelf-life/',
            # 'http://www.eatbydate.com/sour-cream-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/baking/how-long-does-crisco-last-shelf-life-expiration-date-storage-tips/',
            # 'http://www.eatbydate.com/can-you-eat-green-potatoes/',
            # 'http://www.eatbydate.com/grains/baked-goods/cheesecake-shelf-life/',
            # 'http://www.eatbydate.com/how-long-do-sprinkles-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-do-oysters-last//',
            # 'http://www.eatbydate.com/fruits/fresh/pomegranate//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/asparagus/',
            # 'http://www.eatbydate.com/other/baking/how-long-does-vanilla-extract-last-shelf-life//',
            # 'http://www.eatbydate.com/how-long-do-sprinkles-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-strawberries-last/',
            # 'http://www.eatbydate.com/fruits/fresh/figs',
            # 'http://www.eatbydate.com/stuffing-shelf-life-expiration-date',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/salad-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-do-onions-last-shelf-life/',
            # 'http://www.eatbydate.com/other/leftovers//',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-oranges-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/chocolate-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-does-crisco-last-shelf-life-expiration-date-storage-tips//',
            # 'http://www.eatbydate.com/fruits/fresh/cantaloupe//', 'http://www.eatbydate.com/dairy/',
            # 'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/spices/how-long-does-ginger-last-shelf-life/',
            # 'http://www.eatbydate.com/proteins/nuts/sunflower-seeds//', 'http://www.eatbydate.com/dairy/eggs/',
            # 'http://www.eatbydate.com/how-long-does-beer-last-shelf-life/',
            # 'http://www.eatbydate.com/uses-plastic-bags/', 'http://www.eatbydate.com/bacon-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-strawberries-last//',
            # 'http://www.eatbydate.com/how-long-does-mustard-last/',
            # 'http://www.eatbydate.com/other/baking/cookie-dough/',
            # 'http://www.eatbydate.com/oreos-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-oranges-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/grains/baked-goods/cheesecake-shelf-life//',
            # 'http://www.eatbydate.com/proteins/seafood/', 'http://www.eatbydate.com/pesto//',
            # 'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/dairy/milk/buttermilk//',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-jam-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-does-condensed-milk-last-shelf-life/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/mushrooms/',
            # 'http://www.eatbydate.com/how-long-does-cranberry-sauce-last/',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-evaporated-milk-last-shelf-life/',
            # 'http://www.eatbydate.com/other/snacks/hummus//', 'http://www.eatbydate.com/shelf-life-definition/',
            # 'http://www.eatbydate.com/how-long-does-chicken-broth-last-shelf-life/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/lemongrass//',
            # 'http://www.eatbydate.com/other/condiments/ketchup-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-does-papaya-last//',
            # 'http://www.eatbydate.com/how-long-does-vanilla-extract-last-shelf-life/',
            # 'http://www.eatbydate.com/other/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/salad-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-bbq-sauce-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-mustard-last//',
            # 'http://www.eatbydate.com/fruits/fresh/blueberries/', 'http://www.eatbydate.com/fruits/',
            # 'http://www.eatbydate.com/fruits/fresh/tomatoes-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-cupcakes-last-shelf-life/',
            # 'http://www.eatbydate.com/proteins/nuts/sesame-seeds//',
            # 'http://www.eatbydate.com/how-long-does-cornstarch-last-shelf-life//',
            # 'http://www.eatbydate.com/proteins/meats/deli-meat-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/salsa-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/chia-seeds/', 'http://www.eatbydate.com/canned-fruit-shelf-life-expiration-date',
            # 'http://www.eatbydate.com/proteins/meats/does-beef-jerky-go-bad/', 'http://www.eatbydate.com/pesto/',
            # 'http://www.eatbydate.com/grains/cereal-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-jam-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/other/condiments/olives/', 'http://www.eatbydate.com/clever-cooking-tricks/',
            # 'http://www.eatbydate.com/how-long-do-coconuts-last-shelf-life/',
            # 'http://www.eatbydate.com/how-long-does-infant-formula-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/snacks/guacamole-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/does-beef-jerky-go-bad//',
            # 'http://www.eatbydate.com/hot-dogs-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-avocados-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/peaches/',
            # 'http://www.eatbydate.com/dairy/cheese/cream-cheese-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/fruits/fresh/apples-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-avocados-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/best-before-date-definition/',
            # 'http://www.eatbydate.com/how-long-does-shrimp-last/',
            # 'http://www.eatbydate.com/cake-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-oil-last/',
            # 'http://www.eatbydate.com/dairy/milk/dairy-coffee-cream-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/vegetables/how-long-does-flour-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/green-beans/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-celery-last-shelf-life//',
            # 'http://www.eatbydate.com/proteins/beans-peas/', 'http://www.eatbydate.com/how-long-does-frosting-last//',
            # 'http://www.eatbydate.com/fruits/fresh/pineapples//',
            # 'http://www.eatbydate.com/how-long-does-salmon-last-shelf-life//',
            #
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-condensed-milk-last-shelf-life//',
            # 'http://www.eatbydate.com/fruits/fresh/passion-fruit//',
            # 'http://www.eatbydate.com/other/sweets/how-long-does-jello-last-shelf-life//',
            # 'http://www.eatbydate.com/grains/quinoa/',
            # 'http://www.eatbydate.com/how-long-do-jelly-beans-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-do-lemons-last/',
            # 'http://www.eatbydate.com/drinks/alcohol/how-long-does-champagne-last-shelf-life/',
            # 'http://www.eatbydate.com/how-long-do-jelly-beans-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-oyster-sauce-last-shelf-life/',
            # 'http://www.eatbydate.com/fruits/fresh/bananas-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/baking/yeast/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/how-long-does-summer-squash-last//',
            # 'http://www.eatbydate.com/other/dry-ice//', 'http://www.eatbydate.com/how-long-does-nori-last-shelf-life/',
            # 'http://www.eatbydate.com/fruits/fresh/pears//',
            # 'http://www.eatbydate.com/mondays-lunch-expired-bean-thread-soup/',
            # 'http://www.eatbydate.com/hard-boiled-eggs-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-does-lettuce-last',
            # 'http://www.eatbydate.com/other/condiments/how-long-do-maraschino-cherries-last-shelf-life//',
            # 'http://www.eatbydate.com/ice-cream-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/other/condiments/how-long-does-coconut-oil-last/',
            # 'http://www.eatbydate.com/vegetables/fresh-vegetables/asparagus//',
            # 'http://www.eatbydate.com/other/condiments/mayonnaise-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/cake-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/proteins/protein-powder//', 'http://www.eatbydate.com/grains/cereal/',
            # 'http://www.eatbydate.com/fruits/fresh/how-long-do-avocados-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/dairy/milk/how-long-does-egg-nog-last-shelf-life-expiration-date/',
            # 'http://www.eatbydate.com/how-long-do-pop-tarts-last-shelf-life-expiration-date//',
            # 'http://www.eatbydate.com/how-long-do-cucumbers-last-shelf-life-expiration-date/',
            'http://www.eatbydate.com/types-of-oatmeal/',
            'http://www.eatbydate.com/drinks/alcohol/how-long-does-beer-last-shelf-life/',
            'http://www.eatbydate.com/fruits/fresh/blueberries'

        ]

        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):

        page = response.url.split("/")[-2]
        filename = 'quotes-%s.html' % page

        filename = 'c'



        response1 = response.css('tr.alt strong::text').getall()
        response2 = response.css('tr.alt td::text').getall()
        response3 = response.css('div.cody-tbl-container th::text').getall()
        counter = -1
        counter1 = 0
    next this.custom_settings = counter1
        for x in response1:
            counter = counter + 1
            if x != "--" and x != " for" and x != "last for" and x != "lasts for" and (response2[counter] != "--") \
                    and (response2[counter] != " for") and (response2[counter] != "last for")and response2[counter]\
                    != "lasts for":

                print(x, response2[counter])
    counter = 0
this "-- and for counter ++" and if Union (set1, set2)
//
        for x in response2:
            counter1 = counter1 + 1
            if x != "--" and x != " for" and x != "last for" and x != "lasts for":
                print(x)


            for x in response2.this(atleasy x != "last for")
                and if open(Union [str, bytes, input()])
        print(response1, response2)
        with open(filename, 'wb') as f:
            f.write(response)
        self.log('Saved file %s' % filename)


