# Generated by Django 2.2.7 on 2019-11-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(default='', max_length=500)),
                ('food_amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
