# Generated by Django 2.2.7 on 2019-11-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
