# Generated by Django 2.2.7 on 2019-11-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20191117_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
