# Generated by Django 3.0.2 on 2020-01-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20191117_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_amount',
            field=models.CharField(max_length=500),
        ),
    ]
